config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  devise_for :customers, controller: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }

  devise_for :admins, controller: {
    registrations: 'admin/registrations',
    sessions: 'admin/sessions',
    passwords: 'admin/passwords'
  }

  scope module: :customer do
    root to: 'homes#top'
    get '/about' => "homes#about"

    resources :add_deliveries, only: %i[index create destroy edit update] do
    end

    resources :customers do
      collection do
        get 'customers/edit' => 'customers#edit'
        patch 'customers' => 'customers#update'
        get '/my_page' => 'customers#show'
        get '/unsubscribe' => 'customers#unsubscribe'
        patch '/withdraw' => 'customers#withdraw'
      end
    end

    resources :into_carts, only: %i[index update destroy create] do
      collection do
        delete 'delete_all'
      end
    end

    resources :items, only: %i[index show] do
      collection do
        get 'search'
      end
    end

    resources :orders, only: %i[new create index show] do
      collection do
        get '/about' => 'orders#about'
        get '/completion' => 'orders#completion'

      end
    end
  end

  namespace :admin do
    resources :items, only: %i[index show new create edit update]
    resources :customers, only: %i[index show edit update]
    resources :genres, only: %i[index show create edit update]
    resources :orders, only: %i[index show update]
    resources :orders_items, only: [:update]
  end


  #https://qiita.com/hirokihello/items/fa82863ab10a3052d2ff
  #https://pikawaka.com/rails/destroy_all
  #https://railsguides.jp/routing.html
  #https://debug-life.net/entry/103
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_items, dependent: :destroy

	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
	validates :charge, :payment, numericality: { only_integer: true }

	enum payjp_id: {"クレジットカード": 0,"銀行振込": 1}
	enum order_status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送待ち": 3, "発送済み": 4}
	#注文ステータス sutasus
	def plus_tax
    @plus_tax_price = price_without * 1.10
    @plus_tax_price.floor
	end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!
  # ログイン済のユーザのみアクセスの許可をする

  # アクションが足りていない気がする
  # カラム 追加、isdelete?系のブーリアンがた
   def index
     @customers = Customer.all
   end

   def show
     @customer = Customer.find(params[:id])
   end

   def update
     @customer = Customer.find(params[:id])
     if @customer.update(customers_params)
       redirect_to admin_customer_path
     else
       render :edit
     end
   end

   def edit
     @customer = Customer.find(params[:id])
   end

   private



   def customers_params
     # permit以下、key取得、update用
     params.require(:customer).permit(:surname, :firstname, :surname_kana, :firstname_kana,:postal_code,:address,:phone_number,:is_active)
   end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.order('id DESC').page(params[:page]).per(10)
    @order_items = OrderItem.all
  end
  def show
    @orders = Order.all
    @order = Order.find(params[:id])
    @order_items = OrderItem.all
  end


  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.order_status == '入金確認'
        @order.order_items.each do |order_item|
          order_item.update(prod_status: '製作待ち')
        end
      end
      redirect_to admin_order_path(@order)
    else
      render 'show'
    end
  #   @order_items = OrderItem.all
  #   @order_items.each do |order_item|
  #     order_item.update(prod_status: 1) if @order.id == order_item.order_id
  #   end
  # end
end


  private
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :order_status)
  end
end

app/controllers/customer/add_deliveries_controller.rb
class Customer::AddDeliveriesController < ApplicationController

  def index
   @add_delivery = AddDelivery.new
   @add_deliveries = current_customer.add_deliveries
  end

  def create
    @add_delivery = AddDelivery.new(add_delivery_params)
    @add_delivery.customer_id = current_customer.id
    if @add_delivery.save
      flash.now[:notice] = "新規配送先を登録しました"
      redirect_to add_deliveries_path
    else
      render "edit"
    end
  end

  def destroy
    @add_delivery = AddDelivery.find(params[:id])
    @add_delivery.destroy
    @add_deliveries = current_customer.add_deliveries
    flash.now[:alert] = "配送先を削除しました"
    redirect_to add_deliveries_path
  end

  def edit
    @add_delivery = AddDelivery.find(params[:id])
  end

  def update
    @add_delivery = AddDelivery.find(params[:id])
    if @add_delivery.update(add_delivery_params)
      redirect_to add_deliveries_path
    else
      render :edit
    end
  end

  private

  def add_delivery_params
  	params.require(:add_delivery).permit(:postal_code, :address, :addressee)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!, only: [:edit, :update]

  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = Customer.find(params[:id])
    @customer = current_customer
		if @customer.update(customer_params)
  		  flash[:success] = "登録情報を変更しました"
  		  redirect_to my_page_customers_path
  		else
  		  render "edit"
  		end

  end

  def unsubscribe
  end

  def withdraw
    @customer = current_customer
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用をお待ちしております。"
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:surname, :firstname, :surname_kana, :firstname_kana, :postal_code, :email, :address, :phone_number )
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  RECOMMEND_ITEMS = 4

  def top
    @genres = Genre.all
    @items = Item.all
    @item = @items.sample(RECOMMEND_ITEMS)
    @today_orders = OrderItem.created_today
  end

  def about
  end

end

app/controllers/customer/into_carts_controller.rb
class Customer::IntoCartsController < ApplicationController
   # before_action :setup_cart_item!, only: [:create, :update, :destroy, :destroy_all]

   def index
    @cart_items = IntoCart.where(customer_id: current_customer.id).includes(:item)
    @sum = 0
    @cart_items.each do |cart_item|
     quantity = cart_item.quantity.to_i
     price = cart_item.item.price_without.to_i
     @sum += ((price * quantity) * 1.1).round(2).ceil
    end
   end



   def destroy
     cart_item = IntoCart.find(params[:id])
     cart_item.destroy
     redirect_to into_carts_path
   end

   def delete_all
     cart_items = IntoCart.where(customer_id: current_customer.id)
     # delete_all??desteoy_all??
     cart_items.delete_all
     redirect_to request.referer
     # 要リダイレクト先設定
   end

   def create
    # if IntoCart.where(customer_id: current_customer.id).find_by(item_id: params[:into_cart][:item_id]).blank?
    if IntoCart.find_by(item_id: params[:into_cart][:item_id], customer_id: current_customer.id).blank?
    cart = IntoCart.new
    cart.customer_id = current_customer.id
    cart.item_id = params[:into_cart][:item_id]
    cart.quantity = params[:into_cart][:quantity]
    cart.save
    else
     cart = IntoCart.find_by(customer_id: current_customer.id, item_id: params[:into_cart][:item_id])
     cart.quantity += params[:into_cart][:quantity].to_i
     cart.save

    end
    redirect_to into_carts_path
   end


   def update
     new_quantity = params[:into_cart][:quantity].to_i
     cart = IntoCart.find(params[:id])
     cart.update(quantity: new_quantity)
     redirect_to into_carts_path
   end

  private
   def setup_cart_item!
     @cart_item = current_cart.items.find_by(item_id: params[:item_id])
   end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  before_action :authenticate_customer!, only: [:show]

  def index
    @genres = Genre.all
    @items = Item.all
    @items_index = @items.where(item_status: true).page(params[:page]).per(8)
  end

  def search
    @datas=Item.where(genre_id: params[:search][:value])
  end

  def show
    @items = Item.where(item_status: true).page(params[:page]).per(8)
    @item = Item.find(params[:id])
    @into_cart = IntoCart.new
    @genres = Genre.all
  end


#   private

#   def match(value)
#     Item.where(name: value).or(Item.where(genre_id: value,))
#   end

#   def match(value)
#     Item.where(name:value).or(Item.where(genre_id: value, item_status: true))
#   end

#   def search_for(value)
#   case
#   when 'match'                 #ジャンル検索の場合はmatchで固定してるので、必ず'match'の処理に進みます。
#       match(value)
#   when 'forward'
#       forward(value)
#   when 'backward'
#       backward(value)
#   when 'partical'
#       partical(value)
#   end
#   end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def new
    @order = Order.new
    @add_deliveries = AddDelivery.where(customer: current_customer)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(id: @order)
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id

    if @order.save
      @cart_items = IntoCart.where(customer_id: current_customer.id)
      @cart_items.each do |cart_item|
        @order_item = OrderItem.new
        @order_item.order_id = @order.id
        @order_item.item_id = cart_item.item.id
        @order_item.quantity = cart_item.quantity
        @order_item.save
        cart_item.destroy
      end
    end
    redirect_to completion_orders_path
  end

  def completion
  end

  def index
    @orders = Order.where(customer_id: current_customer.id).order("id DESC").page(params[:page]).per(10)
    @order_items = OrderItem.all
  end

  def about
    @order = current_customer.orders.new(order_params)
    @into_carts = IntoCart.where(customer: current_customer)
    @order = Order.new(order_params)

    @add_deliveries = AddDelivery.where(customer: current_customer)
    #@into_carts = IntoCart.all
    if params[:order][:post] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.addressee = current_customer.surname +
                        current_customer.firstname

    elsif params[:order][:post] == "add_deliveries"
      name = AddDelivery.find(params[:order][:add_delivery_id])
      @order.postal_code = name.postal_code
      @order.address = name.address
      @order.addressee = name.addressee

    elsif params[:post] == "new_address"
      @order = AddDelivery.new
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.addressee = params[:order][:addressee]
      @order.save
    end

    @into_carts = IntoCart.where(customer_id: current_customer.id).includes(:item)
    @sum = 0
    @into_carts.each do |cart|
      cart.quantity = cart.quantity.to_i
      price = cart.item.price_without.to_i
      @sum += ( price * cart.quantity )
    end

  end

  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :addressee, :payjp_id, :payment, :surname, :firstname)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/add_deliveries_helper.rb
module Customer::AddDeliveriesHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
  def full_name(customer)
    "#{customer.surname} #{customer.firstname}"
  end
  
  def kana_full_name(customer)
    "#{customer.surname_kana} #{customer.firstname_kana}" 
  end
end

app/views/customer/orders/about.html.erb
<h2 class="head-line title_h2 text-center">注文情報確認</h2>
<div calss="row">
  <div class="col-xs-9">
      <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @into_carts.each do |cart| %>
            <tr>
              <!--商品名-->
              <td class="text-left">
                <%= attachment_image_tag(cart.item, :image, size: "60x50", fallback: "no_image.jpg") %>
                <%= cart.item.name %>
              </td>
              <!--単価(税込)-->
              <td class="text-right">
                ¥<%= ((cart.item.price_without*1.1).round(2)).ceil.to_s(:delimited) %>
                <%#= price_with(cart.item.price_with).to_s(:delimited) %>
              </td>
              <!--数量-->
              <td class="text-right">
                  <%= cart.quantity %>
              </td>
              <!--小計-->
              <td class="text-right">
                ¥<%= (((cart.quantity.to_i * cart.item.price_without.to_i)*1.1).round(2)).ceil  %>
              <!--¥<%#= price_with(cart.item.price_with) * cart.quantity.to_s(:delimited) %>-->
                <%#= cart.item.price_without.to_s(:delimited) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-3 billing">
      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">送料</th>
            <td class="text-right col-xs-5">800</td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-right">¥<%= ((@sum*1.1).round(2)).ceil.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse %></td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-right">¥<%= (((@sum + 800)*1.1).round(2)).ceil.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse %></td>
          </tr>
      </table>
    </div>
    <div class="col-xs-9 billing">
      <table class="table table-hover table-condensed table-bordered">
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= @order.payjp_id %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            〒<%= @order.postal_code %> <%= @order.address %>　<%= @order.addressee %>&nbsp;様/御中
          </td>
        </tr>
      </table>
      <div class ="col-xs-11">
      <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :postal_code %>
        <%= f.hidden_field :address %>
        <%= f.hidden_field :addressee %>
        <%= f.hidden_field :payjp_id %>
        <%= f.hidden_field :charge, :value => @charge %>
        <%= f.hidden_field :payment, :value => @sum %>
        <%= f.hidden_field :order_status, :value => @order_status %>
        <%= link_to "注文情報入力へ戻る", new_order_path, data: {"turbolinks" => false}, class: "btn btn-info col-xs-3 back" %>
          <i class="fas fa-shipping-fast fa-2x"></i>
        <%= f.submit "購入を確定する", class: "btn btn-warning center-block col-xs-5" %>
      <% end %>
      </div>
      <div class ="col-xs-11">
      <%# end %>
      </div>
    <%# else %>
        <p><%= link_to "商品一覧", items_path %>へ</p>
    <%# end %>
  </div>
</div>

app/views/customer/orders/completion.html.erb
<h1 class="text-center completion">ご購入ありがとうございました！</h1>

app/views/customer/orders/index.html.erb
<div class="container">
  <div calss="row">
    <h2 class="header-background col-xs-3 col-xs-offset-2">注文履歴一覧</h2>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <% if @orders.present? %>
      <table class="table table-hover table-bordered table-condensed">
        <thead>
          <tr class="info">
            <th><i class="fas fa-calendar-day"></i>注文日</th>
            <th>配送先</th>
            <th>注文商品</th>
            <th>支払金額</th>
            <th>ステータス</th>
            <th>注文詳細</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td>
      		    <%= order.created_at.strftime('%Y/%m/%d') %>
      		  </td>
      		  <td class="text-left">
      		    <%= order.postal_code %><br>
      		    <%= order.address %><br>
      		    <%= order.addressee %>
      		  </td>
      		  <td>
      		    <% order.order_items.each do |order_item| %>
      		    <%= order_item.item.name %><br>
      		    <% end %>
      		  </td>
      		  <td class="text-right">
              <%= (order.payment + 800).to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse  %>円
      		  </td>
      		  <td>
      		    <%= order.order_status %>
      		  </td>
           	<td>
         	    <%= link_to "注文詳細", order_path(order.id), class: "glyphicon glyphicon-zoom-in btn btn-success" %>
         	  </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
        <p>注文履歴がありません。</p>
      <% end %>
    </div>

  </div>
</div>

app/views/customer/orders/new.html.erb
<h4 class="customer-index">注文情報入力</h4>

<div class="orders-new-info">
  <div class="">
    <h4 class="orders-new-info-index">支払方法</h4>
    <div>
      <%= form_with model:@order, url:about_orders_path, method: :get, local: true  do |f| %>


        <div class="orders-new-payment-select">
          <p>
            <%= f.radio_button :payjp_id, "クレジットカード", checked: true %>
            <%= f.label :payjp_id, "クレジットカード" %>
          </p>
          <p>
            <%= f.radio_button :payjp_id, "銀行振込" %>
            <%= f.label :payjp_id, "銀行振込" %>
          </p>
        </div>

        <div class="">
          <h4 class="orders-new-info-index">お届け先</h4>
          <div class="orders-new-select">
            <div class="orders-new-costomer-address">
              <div>
                <%= f.radio_button :post, "residence"  %>
                <%= f.label :post, "ご自身の住所", checked: true %><br>
                <%= "〒#{current_customer.postal_code} #{current_customer.address}" %>
              </div>
              <p class="orders-new-address">
                <%= "#{current_customer.surname} #{current_customer.firstname}" %>
              </p>
            </div>
          </div>
        </div>

        <div class="orders-new-address-select">
          <%= f.radio_button :post, "add_deliveries" %>
          <%= f.label :post, "登録済住所から選択" %><br>
          <%= f.collection_select(:add_delivery_id, @add_deliveries, :id, :address) %>
        </div>

        　   <div class="orders-new-address-input">
      　     <div>
      <%= f.radio_button :post, "new_address" %>
      <%= f.label :post, "新しいお届け先" %><br>

      <div class="field form-group col-xs-11">
        <%= f.label :postal_code, "郵便番号(ハイフンなし)", class: "col-sm-4 control-label" %>
        <%= f.text_field :postal_code, class: "col-sm-3 form-control-static postal_code" %>
      </div>

      <div class="field form-group col-xs-11">
        <%= f.label :address, "住所", class: "col-sm-4 control-label" %>
        <%= f.text_field :address, class: "col-sm-8 form-control-static address" %>
      </div>

      <div class="field form-group col-xs-11">
        <%= f.label :addressee,"宛名", class: "col-sm-4 control-label" %>
        <%= f.text_field :addressee, class: "col-sm-4 form-control-static" %>
      </div>
    </div>

        <div class="orders-new-confirm-button">
          <div class="btn col-xs-6">
            <%= f.submit "確認画面へ進む", class: "btn btn-success col-xs-5" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customer/orders/show.html.erb
<h2 class="head-line title_h2 text-center">注文履歴詳細</h2>
<div calss="row">
  <% if @order.present? %>
    <div class="col-xs-8">
    	<strong><i class="far fa-user"></i>注文情報</strong>
  	    <table class="table table-bordered table-condensed">
          <tbody>
              <tr>
                <th class="info">注文日</th>
          	  <td class="text-left"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
              </tr>
              <tr>
              　<th class="info">配送先</th>
                 <td class="text-left"><%= @order.postal_code %><br>
                	  <%= @order.address %><br>
                	  <%= @order.addressee %>
                </td>
              </tr>
              <tr>
              　<th class="info">支払方法</th>
                <td class="text-left"><%= @order.payjp_id %></td>
              </tr>
              <tr>
                <th class="info">ステータス</th>
                <td class="text-left"><%= @order.order_status %></td>
              </tr>
          </tbody>
        </table>

    </div>

    <div class="col-xs-3 col-xs-offset-1 billing">
      <strong><i class="fas fa-yen-sign"></i>請求情報</strong>

        	<table class="table  table-bordered table-condensed">
            <tr>
              <th class="info">商品合計</th>
              <td class="text-right col-xs-5"><%= @order.payment.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse  %>円</td>
            </tr>
            <tr>
              <th class="info">配送料</th>
              <td class="text-right col-xs-5"><%= @order.charge %>円</td>
            </tr>
            <tr>
              <th class="info">ご請求金額</th>
              <td class="text-right col-xs-5"><%= (@order.payment + @order.charge).to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse  %>円</td>
            </tr>
        </table>
    </div>
    <div class="col-xs-7 order-details">
    	<strong><i class="fas fa-store"></i>注文内容</strong>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
  	      <tr class="info">
  	      	<th>商品</th>
  	        <th>単価(税込)</th>
  	      	<th>個数</th>
  	      	<th>小計</th>
  	      </tr>
        	</thead>
        	<tbody>
          <% @order_items.each do |oi| %>
            <tr>
  	        <td><%= oi.item.name %></td>

  	        <td class="text-right"><%= oi.item.price_without.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse %>円</td>
  	        <td class="text-right"><%= oi.quantity %></td>
  	        <td class="text-right"><%= (oi.quantity.to_i * oi.item.price_without.to_i).to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse  %>円</td>
            </tr>
          <% end %>
          </tbody>
        </table>


    </div>
    <% if customer_signed_in? %>
      <%= link_to "注文履歴一覧へ戻る", orders_path, class: "btn btn-info btn-lg order-index-back" %>
    <% else %>
      <%= link_to "会員詳細へ戻る", admin_customer_path, class: "btn btn-info order-index-back" %>
    <% end %>
  <% else %>
    <p>注文履歴がありません。</p>
  <% end %>
</div>