config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  devise_for :customers, controller: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }

  devise_for :admins, controller: {
    registrations: 'admin/registrations',
    sessions: 'admin/sessions',
    passwords: 'admin/passwords'
  }

  scope module: :customer do
    root to: 'homes#top'
    get '/about' => "homes#about"

    resources :add_deliveries, only: %i[index create destroy edit update] do
    end

    resources :customers do
      collection do
        get 'customers/edit' => 'customers#edit'
        patch 'customers' => 'customers#update'
        get '/my_page' => 'customers#show'
        get '/unsubscribe' => 'customers#unsubscribe'
        patch '/withdraw' => 'customers#withdraw'
      end
    end

    resources :into_carts, only: %i[index update destroy create] do
      collection do
        delete 'delete_all'
      end
    end

    resources :items, only: %i[index show] do
      collection do
        get 'search'
      end
    end

    resources :orders, only: %i[new create index show] do
      collection do
        get '/about' => 'orders#about'
        get '/completion' => 'orders#completion'

      end
    end
  end

  namespace :admin do
    resources :items, only: %i[index show new create edit update]
    resources :customers, only: %i[index show edit update]
    resources :genres, only: %i[index show create edit update]
    resources :orders, only: %i[index show update]
    resources :orders_items, only: [:update]
  end


  #https://qiita.com/hirokihello/items/fa82863ab10a3052d2ff
  #https://pikawaka.com/rails/destroy_all
  #https://railsguides.jp/routing.html
  #https://debug-life.net/entry/103
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :add_deliveries, dependent: :destroy
  has_many :orders
  has_many :into_carts, dependent: :destroy
  has_many :into_items, dependent: :destroy

  attachment :image
  validates :surname, :firstname, :surname_kana, :firstname_kana,
            :address, :phone_number,
            presence: true

  # 郵便番号は数字のみ許可。ハイフンやカッコは認めない
  validates :postal_code, length:{is: 7}, numericality: { only_integer: true }

  # 電話番号は数字のみ許可。ハイフンやカッコは認めない
  validates :phone_number, numericality: { only_integer: true }

  #カナ氏名はカタカナ意外不可
  validates :surname_kana, :firstname_kana,
    format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

  #パスワードvaridate＋再確認
  #validates :password, confirmation: true
  #validates :password_confirmation, presence: true

  validates :is_active, inclusion: { in: [true, false] }

  enum user_status: { '有効': true, '退会済': false }

  def active_for_authentication?
    super && self.user_status == '有効'
  end


  #パスワードvaridate＋再確認⇨これをつけるとmypageでupdateできなくなる⇨なぜ？
  # validates :password, confirmation: true
  # validates :password_confirmation, presence: true

  # has_many :add_deliveries, dependent: :destroy
  # has_many :orders
  # has_many :into_items, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!
  # ログイン済のユーザのみアクセスの許可をする

  # アクションが足りていない気がする
  # カラム 追加、isdelete?系のブーリアンがた
   def index
     @customers = Customer.all
   end

   def show
     @customer = Customer.find(params[:id])
   end

   def update
     @customer = Customer.find(params[:id])
     if @customer.update(customers_params)
       redirect_to admin_customer_path
     else
       render :edit
     end
   end

   def edit
     @customer = Customer.find(params[:id])
   end

   private



   def customers_params
     # permit以下、key取得、update用
     params.require(:customer).permit(:surname, :firstname, :surname_kana, :firstname_kana,:postal_code,:address,:phone_number,:is_active)
   end

end

app/controllers/customer/add_deliveries_controller.rb
class Customer::AddDeliveriesController < ApplicationController

  def index
   @add_delivery = AddDelivery.new
   @add_deliveries = current_customer.add_deliveries
  end

  def create
    @add_delivery = AddDelivery.new(add_delivery_params)
    @add_delivery.customer_id = current_customer.id
    if @add_delivery.save
      flash.now[:notice] = "新規配送先を登録しました"
      redirect_to add_deliveries_path
    else
      render "edit"
    end
  end

  def destroy
    @add_delivery = AddDelivery.find(params[:id])
    @add_delivery.destroy
    @add_deliveries = current_customer.add_deliveries
    flash.now[:alert] = "配送先を削除しました"
    redirect_to add_deliveries_path
  end

  def edit
    @add_delivery = AddDelivery.find(params[:id])
  end

  def update
    @add_delivery = AddDelivery.find(params[:id])
    if @add_delivery.update(add_delivery_params)
      redirect_to add_deliveries_path
    else
      render :edit
    end
  end

  private

  def add_delivery_params
  	params.require(:add_delivery).permit(:postal_code, :address, :addressee)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!, only: [:edit, :update]

  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = Customer.find(params[:id])
    @customer = current_customer
		if @customer.update(customer_params)
  		  flash[:success] = "登録情報を変更しました"
  		  redirect_to my_page_customers_path
  		else
  		  render "edit"
  		end

  end

  def unsubscribe
  end

  def withdraw
    @customer = current_customer
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用をお待ちしております。"
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:surname, :firstname, :surname_kana, :firstname_kana, :postal_code, :email, :address, :phone_number )
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  RECOMMEND_ITEMS = 4

  def top
    @genres = Genre.all
    @items = Item.all
    @item = @items.sample(RECOMMEND_ITEMS)
    @today_orders = OrderItem.created_today
  end

  def about
  end

end

app/controllers/customer/into_carts_controller.rb
class Customer::IntoCartsController < ApplicationController
   # before_action :setup_cart_item!, only: [:create, :update, :destroy, :destroy_all]

   def index
    @cart_items = IntoCart.where(customer_id: current_customer.id).includes(:item)
    @sum = 0
    @cart_items.each do |cart_item|
     quantity = cart_item.quantity.to_i
     price = cart_item.item.price_without.to_i
     @sum += ((price * quantity) * 1.1).round(2).ceil
    end
   end



   def destroy
     cart_item = IntoCart.find(params[:id])
     cart_item.destroy
     redirect_to into_carts_path
   end

   def delete_all
     cart_items = IntoCart.where(customer_id: current_customer.id)
     # delete_all??desteoy_all??
     cart_items.delete_all
     redirect_to request.referer
     # 要リダイレクト先設定
   end

   def create
    # if IntoCart.where(customer_id: current_customer.id).find_by(item_id: params[:into_cart][:item_id]).blank?
    if IntoCart.find_by(item_id: params[:into_cart][:item_id], customer_id: current_customer.id).blank?
    cart = IntoCart.new
    cart.customer_id = current_customer.id
    cart.item_id = params[:into_cart][:item_id]
    cart.quantity = params[:into_cart][:quantity]
    cart.save
    else
     cart = IntoCart.find_by(customer_id: current_customer.id, item_id: params[:into_cart][:item_id])
     cart.quantity += params[:into_cart][:quantity].to_i
     cart.save

    end
    redirect_to into_carts_path
   end


   def update
     new_quantity = params[:into_cart][:quantity].to_i
     cart = IntoCart.find(params[:id])
     cart.update(quantity: new_quantity)
     redirect_to into_carts_path
   end

  private
   def setup_cart_item!
     @cart_item = current_cart.items.find_by(item_id: params[:item_id])
   end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  before_action :authenticate_customer!, only: [:show]

  def index
    @genres = Genre.all
    @items = Item.all
    @items_index = @items.where(item_status: true).page(params[:page]).per(8)
  end

  def search
    @datas=Item.where(genre_id: params[:search][:value])
  end

  def show
    @items = Item.where(item_status: true).page(params[:page]).per(8)
    @item = Item.find(params[:id])
    @into_cart = IntoCart.new
    @genres = Genre.all
  end


#   private

#   def match(value)
#     Item.where(name: value).or(Item.where(genre_id: value,))
#   end

#   def match(value)
#     Item.where(name:value).or(Item.where(genre_id: value, item_status: true))
#   end

#   def search_for(value)
#   case
#   when 'match'                 #ジャンル検索の場合はmatchで固定してるので、必ず'match'の処理に進みます。
#       match(value)
#   when 'forward'
#       forward(value)
#   when 'backward'
#       backward(value)
#   when 'partical'
#       partical(value)
#   end
#   end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def new
    @order = Order.new
    @add_deliveries = AddDelivery.where(customer: current_customer)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(id: @order)
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id

    if @order.save
      @cart_items = IntoCart.where(customer_id: current_customer.id)
      @cart_items.each do |cart_item|
        @order_item = OrderItem.new
        @order_item.order_id = @order.id
        @order_item.item_id = cart_item.item.id
        @order_item.quantity = cart_item.quantity
        @order_item.save
        cart_item.destroy
      end
    end
    redirect_to completion_orders_path
  end

  def completion
  end

  def index
    @orders = Order.where(customer_id: current_customer.id).order("id DESC").page(params[:page]).per(10)
    @order_items = OrderItem.all
  end

  def about
    @order = current_customer.orders.new(order_params)
    @into_carts = IntoCart.where(customer: current_customer)
    @order = Order.new(order_params)

    @add_deliveries = AddDelivery.where(customer: current_customer)
    #@into_carts = IntoCart.all
    if params[:order][:post] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.addressee = current_customer.surname +
                        current_customer.firstname

    elsif params[:order][:post] == "add_deliveries"
      name = AddDelivery.find(params[:order][:add_delivery_id])
      @order.postal_code = name.postal_code
      @order.address = name.address
      @order.addressee = name.addressee

    elsif params[:post] == "new_address"
      @order = AddDelivery.new
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.addressee = params[:order][:addressee]
      @order.save
    end

    @into_carts = IntoCart.where(customer_id: current_customer.id).includes(:item)
    @sum = 0
    @into_carts.each do |cart|
      cart.quantity = cart.quantity.to_i
      price = cart.item.price_without.to_i
      @sum += ( price * cart.quantity )
    end

  end

  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :addressee, :payjp_id, :payment, :surname, :firstname)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/add_deliveries_helper.rb
module Customer::AddDeliveriesHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
  def full_name(customer)
    "#{customer.surname} #{customer.firstname}"
  end
  
  def kana_full_name(customer)
    "#{customer.surname_kana} #{customer.firstname_kana}" 
  end
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/into_carts_helper.rb
module Customer::IntoCartsHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h3 class="header-background col-xs-5"><%= @customer.surname %><%= @customer.firstname %>さんの会員情報編集</h3>
  </div>
  <div class="row">
    <div class="col-xs-offset-1 col-xs-11">

      <%= form_for(@customer, url:admin_customer_path, method: :patch) do |f| %>
        <div class="row form-group">
          <label class="control-label col-xs-2">会員ID</label>
          <div class="col-xs-3">
            <%= @customer.id %>
          </div>
        </div>

        <div class="row form-group">
          <label class="control-label col-xs-2">氏名</label>
          <div class="col-xs-6">
            <%= f.text_field :surname, autofocus: true, autocomplete: "last_name" %>
            <%= f.text_field :firstname, autofocus: true, autocomplete: "first_name" %>
          </div>
        </div>

        <div class="row form-group">
          <label class="control-label col-xs-2">フリガナ</label>
          <div class="col-xs-6">
            <%= f.text_field :surname_kana, autofocus: true, autocomplete: "last_name_kana" %>
            <%= f.text_field :firstname_kana, autofocus: true, autocomplete: "first_name_kana" %>
          </div>
        </div>

        <div class="row form-group">
          <label class="control-label col-xs-2">郵便番号</label>
          <div class="col-xs-3">
            <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
          </div>
        </div>

        <div class="row form-group">
          <label class="control-label col-xs-2">住所</label>
          <div class="col-xs-3">
            <%= f.text_field :address, autofocus: true, autocomplete: "address", :size => "60*60" %>
          </div>
        </div>

        <div class="row form-group">
          <label class="control-label col-xs-2">電話番号</label>
          <div class="col-xs-3">
            <%= f.telephone_field :phone_number, autofocus: true, autocomplete: "phone" %>
          </div>
        </div>

        <div class="row form-group">
          <label class="control-label col-xs-2">メールアドレス</label>
          <div class="col-xs-3">
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>
        </div>

        <div class="row form-group">
          <div class="col-xs-3">
            <%= f.label :"会員ステータス" %>
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "退会済み", {value: :false, style: "display: inline-block;"} %>
            <%#= f.select :is_active ,[['有効',true],['退会済み',false]] %>
          </div>
        </div>

        <div class="actions">
          <%= f.submit '変更を保存する' ,class: "btn btn-primary" %>
        </div>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="header-background col-xs-2 col-xs-offset-1">会員一覧</h2>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <table class="table table-hover table-inverse">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <%= customer.surname %> <%= customer.firstname %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active == TRUE %>
                <%= '有効' %>
              <% else %>
                <%= '退会' %>
              <% end %>
            </td>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="header-background col-xs-offset-1 col-xs-4"><%= @customer.surname %><%= @customer.firstname %>さんの会員詳細</h3>
  </div>
  <div class="row">
    <div class="col-xs-offset-1 col-xs-8">
      <table class="table">
        <tr class="active">
        <tr>
          <td>顧客ID</td>
          <td>
            <%= @customer.id %>
            <% if @customer.is_active == TRUE %>
              <span class="badge" style="background:#58aee0;">有効会員</span>
            <% else %>
              <span class="badge" style="background:#d72238;">退会会員</span>
            <% end %>
          </td>
        </tr>

        <tr>
          <td>氏名</td>
          <td><%= @customer.surname %> <%= @customer.firstname %></td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td><%= @customer.surname_kana %> <%= @customer.firstname_kana %></td>
        </tr>

        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>

        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>

        <tr>
          <td>電話番号</td>
          <td><%= @customer.phone_number %></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
      </table>

      <%= link_to edit_admin_customer_path(@customer), data: {"turbolinks" => false} do %>
        <span class="btn btn-primary">編集する</span>
      <% end %>

      <%= link_to admin_orders_path(customer_id: @customer.id) do %>
        <span class="btn btn-primary">注文履歴一覧を見る</span>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>