config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  devise_for :customers, controller: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }

  devise_for :admins, controller: {
    registrations: 'admin/registrations',
    sessions: 'admin/sessions',
    passwords: 'admin/passwords'
  }

  scope module: :customer do
    root to: 'homes#top'
    get '/about' => "homes#about"

    resources :add_deliveries, only: %i[index create destroy edit update] do
    end

    resources :customers do
      collection do
        get 'customers/edit' => 'customers#edit'
        patch 'customers' => 'customers#update'
        get '/my_page' => 'customers#show'
        get '/unsubscribe' => 'customers#unsubscribe'
        patch '/withdraw' => 'customers#withdraw'
      end
    end

    resources :into_carts, only: %i[index update destroy create] do
      collection do
        delete 'delete_all'
      end
    end

    resources :items, only: %i[index show] do
      collection do
        get 'search'
      end
    end

    resources :orders, only: %i[new create index show] do
      collection do
        get '/about' => 'orders#about'
        get '/completion' => 'orders#completion'

      end
    end
  end

  namespace :admin do
    resources :items, only: %i[index show new create edit update]
    resources :customers, only: %i[index show edit update]
    resources :genres, only: %i[index show create edit update]
    resources :orders, only: %i[index show update]
    resources :orders_items, only: [:update]
  end


  #https://qiita.com/hirokihello/items/fa82863ab10a3052d2ff
  #https://pikawaka.com/rails/destroy_all
  #https://railsguides.jp/routing.html
  #https://debug-life.net/entry/103
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_items, dependent: :destroy

	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
	validates :charge, :payment, numericality: { only_integer: true }

	enum payjp_id: {"クレジットカード": 0,"銀行振込": 1}
	enum order_status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送待ち": 3, "発送済み": 4}
	#注文ステータス sutasus
	def plus_tax
    @plus_tax_price = price_without * 1.10
    @plus_tax_price.floor
	end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.order('id DESC').page(params[:page]).per(10)
    @order_items = OrderItem.all
  end
  def show
    @orders = Order.all
    @order = Order.find(params[:id])
    @order_items = OrderItem.all
  end


  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.order_status == '入金確認'
        @order.order_items.each do |order_item|
          order_item.update(prod_status: '製作待ち')
        end
      end
      redirect_to admin_order_path(@order)
    else
      render 'show'
    end
  #   @order_items = OrderItem.all
  #   @order_items.each do |order_item|
  #     order_item.update(prod_status: 1) if @order.id == order_item.order_id
  #   end
  # end
end


  private
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :order_status)
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def new
    @order = Order.new
    @add_deliveries = AddDelivery.where(customer: current_customer)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(id: @order)
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id

    if @order.save
      @cart_items = IntoCart.where(customer_id: current_customer.id)
      @cart_items.each do |cart_item|
        @order_item = OrderItem.new
        @order_item.order_id = @order.id
        @order_item.item_id = cart_item.item.id
        @order_item.quantity = cart_item.quantity
        @order_item.save
        cart_item.destroy
      end
    end
    redirect_to completion_orders_path
  end

  def completion
  end

  def index
    @orders = Order.where(customer_id: current_customer.id).order("id DESC").page(params[:page]).per(10)
    @order_items = OrderItem.all
  end

  def about
    @order = current_customer.orders.new(order_params)
    @into_carts = IntoCart.where(customer: current_customer)
    @order = Order.new(order_params)

    @add_deliveries = AddDelivery.where(customer: current_customer)
    #@into_carts = IntoCart.all
    if params[:order][:post] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.addressee = current_customer.surname +
                        current_customer.firstname

    elsif params[:order][:post] == "add_deliveries"
      name = AddDelivery.find(params[:order][:add_delivery_id])
      @order.postal_code = name.postal_code
      @order.address = name.address
      @order.addressee = name.addressee

    elsif params[:post] == "new_address"
      @order = AddDelivery.new
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.addressee = params[:order][:addressee]
      @order.save
    end

    @into_carts = IntoCart.where(customer_id: current_customer.id).includes(:item)
    @sum = 0
    @into_carts.each do |cart|
      cart.quantity = cart.quantity.to_i
      price = cart.item.price_without.to_i
      @sum += ( price * cart.quantity )
    end

  end

  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :addressee, :payjp_id, :payment, :surname, :firstname)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="header-background col-xs-3 col-xs-offset-1">注文履歴一覧</h2>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id) do %>
                <%= order.created_at.strftime('%Y/%m/%d %H:%M') %>
              <% end %>
            </td>
            <td><%= order.customer.surname %><%= order.customer.firstname %></td>
            <td><%= order.order_items.all.sum(:quantity) %></td>
            <td><%= order.order_status %></td>
            </td>
          </tr>
          <% end %>

        </tbody>
      </table>
    </div>
    <%= paginate(@orders) %>
  </div>
</div>

app/views/admin/orders/show.html.erb
  <div class="container">
  <div class="row">

    <div class="row">
      <h2 class="header-background col-xs-3 col-xs-offset-1">注文履歴詳細</h2>
    </div>

    <div class="row">
      <div class="row">
        <div class="col-xs-2">
          <h4>購入者</h4>
        </div>
        <div class="col-xs-8">
          <h4>
            <%= link_to admin_customer_path do %>
              <%= @order.customer.surname %>　<%= @order.customer.firstname %>
            <% end %>
          </h4>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-2">
          <h4>配送先<h4>
        </div>
        <div class="col-xs-8">
          <div class="row">
            <h4>
              〒：<%= @order.postal_code %>
              住所：<%= @order.address %>
            </h4>
          </div>
          <div class="row">
            <h4>名前：<%= @order.addressee %></h4>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-2">
          <h4>支払い方法</h4>
        </div>
        <div class="col-xs-8">
          <h4>
            <%= @order.payjp_id %>
          </h4>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-2">
          <h4>注文ステータス</h4>
        </div>
        <div class="col-xs-8">
          <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
            <%= f.select :order_status,Order.order_statuses.keys.to_a %>
            <%= f.submit "更新", class: "btn btn-sm btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-9">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>ID</th>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th colspan="5">製作ステータス</th>
            </tr>
          </thead>
          <tbody>
          <% @order_items.each do |oi| %>
            <tr>
              <td>
                id:<%= oi.id %>
              </td>
              <td>
                <%= oi.item.name %>
              </td>
              <td>
                <%= ((oi.item.price_without).to_i * 1.1).round %>
              </td>
              <td>
                <%= oi.quantity %>
              </td>
              <td>
                <%= @syoukei = ((oi.item.price_without).to_i * 1.1 * (oi.quantity).to_i).round %>
              </td>
              <td>
              <%= form_with model: oi, url: admin_orders_item_path(oi), method: :patch, local: true do |f| %>
                <%= f.select :prod_status, OrderItem.prod_statuses.keys %>
                <%= f.submit "更新", class: "btn btn-sm btn-primary" %>
              <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <div class="col-xs-3">

        <div class="row">
          <div class="col-xs-7">
            <h4>商品合計</h4>
          </div>
          <div class="col-xs-5">
            <h4>
              <%= @order.payment  %>円
            </h4>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-7">
            <h4>送料</h4>
          </div>
          <div class="col-xs-5">
            <h4>800円</h4>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-7">
            <h4>請求額合計</h4>
          </div>
          <div class="col-xs-5">
            <h4>
              <%=@order.payment.to_i + 800 %>円
            </h4>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>